# Generated by Django 2.2 on 2019-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='стоимость'),
        ),
    ]
