# Generated by Django 2.2 on 2019-05-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='price',
            new_name='price_basket',
        ),
    ]
