# Generated by Django 2.2 on 2019-04-29 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_descriptionhtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptionHTML',
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='описание'),
        ),
    ]
